name: ci-v25
on:
    push:
        tags:
            - 'v*'
jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix: 
              include:
                - stack: 'stacks/sugar25/php83-local-build.yml'
                  version: 25.1
                  php: 8.3.14
                - stack: 'stacks/sugar25/php84-local-build.yml'
                  version: 25.1
                  php: 8.4.4
        steps:
            - run: sudo sysctl -w vm.max_map_count=262144
            - run: echo '127.0.0.1 docker.local' | sudo tee -a /etc/hosts
            - uses: actions/checkout@v3
            - run: cp -r ./tests/web_tests ./data/app/sugar/
            - run: ./tests/start.sh ${{ matrix.stack }}
            - run: ./tests/web_tests.sh ${{ matrix.stack }} ${{ matrix.version }} ${{ matrix.php }}
            - run: ./tests/stop.sh ${{ matrix.stack }}

    docker:
        strategy:
            fail-fast: true
            matrix:
                include:
                - dockercontext: ./images/php/8314/apache
                  image: umar-ingka108/sugardockerized
                  prefix: php8.3.14-apache-
                - dockercontext: ./images/php/8314/cron
                  image: umar-ingka108/sugardockerized
                  prefix: php8.3.14-cron-
                - dockercontext: ./images/mysql/8032
                  image: umar-ingka108/sugardockerized
                  prefix: mysql8.0.32-
                - dockercontext: ./images/permissions
                  image: umar-ingka108/sugardockerized
                  prefix: permissions-
                - dockercontext: ./images/testsmtp
                  image: umar-ingka108/sugardockerized
                  prefix: testsmtp-
                - dockercontext: ./images/php/844/apache
                  image: umar-ingka108/sugardockerized
                  prefix: php8.4.4-apache-
                - dockercontext: ./images/php/844/cron
                  image: umar-ingka108/sugardockerized
                  prefix: php8.4.4-cron-
                - dockercontext: ./images/mysql/843
                  image: umar-ingka108/sugardockerized
                  prefix: mysql8.4.3-
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v3
          - name: Set up QEMU
            uses: docker/setup-qemu-action@v2
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2
          - name: Login to DockerHub
            if: ${{ github.repository == 'umar-ingka108/SugarDockerized' }}
            uses: docker/login-action@v2
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
          - name: Extract metadata (tags, labels) for Docker
            id: meta
            uses: docker/metadata-action@v4
            with:
                images: ${{ matrix.image }}
                flavor: |
                    latest=true
                    prefix=${{ matrix.prefix }},onlatest=true

          - name: Build and push
            uses: docker/build-push-action@v4
            with:
                context: ${{ matrix.dockercontext }}
                push: ${{ github.repository == 'umar-ingka108/SugarDockerized' && 'true' || 'false' }}
                platforms: 'linux/amd64,linux/arm64'
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
